apiVersion: v1
kind: Pod
metadata:
  name: contact-delete-pod
  labels:
    app: contact-delete
spec:
  containers:
    - name: contact-api-container
      image: lucasmpinho/postechfase3deletecontactapi-contact-api:1
      ports:
        - containerPort: 5013
---
apiVersion: v1
kind: Service
metadata:
  name: contact-delete-service
spec:
  selector:
    app: contact-delete
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5013
      nodePort: 32000
  type: NodePort