version: '3.8'

services:

  # .NET Application
  dotnet_contactupdate_app:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.TechChallenge.ContactDelete.Api/Dockerfile
    container_name: dotnet_contactdelete_app
    restart: always
    ports:
      - "5010:5010"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    networks:
      - app-network

networks:
  app-network:
    external: true