version: '3.8'

services:

  # .NET Application
  dotnet_contactdelete_app:
    build:
      context: .
      dockerfile: src/Postech.GroupEight.TechChallenge.ContactDelete.Api/Dockerfile
    container_name: dotnet_contactdelete_app
    restart: always
    ports:
      - "5013:5013"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    networks:
      - techchallenge-worker-persistency_custom_network

networks:
  techchallenge-worker-persistency_custom_network:
    external: true