name: Tests Workflow

on:
    push:
        branches: ["feature/**"]

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src
    
    unit_tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.UnitTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.UnitTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.UnitTests
    
    integration_tests:
        name: Integration Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.IntegrationTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.IntegrationTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.GroupEight.TechChallenge.ContactDelete.IntegrationTests
